// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ServerSentEvents")]
[assembly: AssemblyProductAttribute("ServerSentEvents")]
[assembly: AssemblyDescriptionAttribute("A Server-Sent Events client implementation for .NET")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
